// Photon
global using LoadBalancingClient_Internal = ObjectPublicIPhotonPeerListenerObStNuStOb1CoObBoDiUnique;
global using PhotonNetwork_Internal = ObjectPublicAbstractSealedObInObStInCo2ObInBoUnique;

// VRC
global using NetworkManager_Internal = MonoBehaviourPrivateAc1AcOb2AcInStHa2Unique;
global using Player_Internal = MonoBehaviourPublicAPOb_vOb_l_pBoOb1BoUnique;
global using PlayerNet_Internal = MonoBehaviour1PublicOb_vInByInBoObBySiObUnique;
global using HudController_Internal = MonoBehaviourPublicObnoObmousCaObhuGa_gUnique;
global using UsedToChangeAvatar = ObjectPublicAbstractSealedVoApSt73APAp73BoFaBoUnique;